# Authors Campaign ALL
[all]
campaign_tracking = "B20WMDE_occeditors_spring_2020_3all"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[all.banners.spring]
filename = "./all/banner.js"
pagename = "B20WMDE_occeditors_spring_2020_3all"
tracking = "B20WMDE_occeditors_spring_2020_3all"

# Authors Campaign Mobile for easily testing mobile view
[all_mobile]
campaign_tracking = "B20WMDE_occeditors_spring_2020_3allm"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[all_mobile.banners.spring]
filename = "./all/banner_mobile.js"
pagename = "B20WMDE_occeditors_spring_2020_3allm"
tracking = "B20WMDE_occeditors_spring_2020_3allm"

# Authors Campaign 2nt, NT=new tasks, Zielgruppe B new users
[nt]
campaign_tracking = "B20WMDE_occeditors_spring_2020_2nt"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[nt.banners.spring]
filename = "./nt/banner.js"
pagename = "B20WMDE_occeditors_spring_2020_2nt"
tracking = "B20WMDE_occeditors_spring_2020_2nt"

# Authors Campaign Mobile for easily testing mobile view
[nt_mobile]
campaign_tracking = "B20WMDE_occeditors_spring_2020_2ntm"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[nt_mobile.banners.spring]
filename = "./nt/banner_mobile.js"
pagename = "B20WMDE_occeditors_spring_2020_2ntm"
tracking = "B20WMDE_occeditors_spring_2020_2ntm"

# Authors Campaign 1cs, CS=community tasks, Zielgruppe A eligible voters
[cs]
campaign_tracking = "B20WMDE_occeditors_spring_2020_1cs"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[cs.banners.spring]
filename = "./cs/banner.js"
pagename = "B20WMDE_occeditors_spring_2020_1cs"
tracking = "B20WMDE_occeditors_spring_2020_1cs"

# Authors Campaign Mobile for easily testing mobile view
[cs_mobile]
campaign_tracking = "B20WMDE_occeditors_spring_2020_1csm"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[cs_mobile.banners.spring]
filename = "./cs/banner_mobile.js"
pagename = "B20WMDE_occeditors_spring_2020_1csm"
tracking = "B20WMDE_occeditors_spring_2020_1csm"