# Authors Campaign
[all]
campaign_tracking = "WMDE_oceditors_spring_2020_2nt" #"WMDE_neweditors_autumn_2019"B20WMDE_oceditors_spring_2020_2nt_cs
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=vector&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[all.banners.spring]
filename = "./all/banner.js" 
pagename = "B20WMDE_oceditors_spring_2020_2nt_cs"
tracking = "WMDE_oceditors_spring_2020_2nt_cs"

# Authors Campaign Mobile for easily testing mobile view
[all_mobile]
campaign_tracking = "WMDE_neweditors_autumn_2019m"
preview_link = "/wiki/Wikipedia:Hauptseite?useskin=minerva&banner=B17WMDE_webpack_prototype&devbanner={{banner}}"
wrapper_template = "wikipedia_org"

[all_mobile.banners.spring]
filename = "./all/banner_mobile.js"
pagename = "B20WMDE_oceditors_spring_2020_2nt_cs_m" #"B19WMDE_neweditors_autumn_2019_lp1m"
tracking = "WMDE_oceditors_spring_2020_2nt_cs_m" #"WMDE_neweditors_autumn_2019_lp1m"